services:

  backend:

    extends:
      file: docker-compose.yml
      service: backend

    env_file:
      - .env.local

    volumes:
      - ./backend:/app

    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
      ]
